/*********************************************************************
 *                                                                   *
 * Copyright (c) 2008-2010 by NIkon DSL.                             *
 * All rights reserved.                                              *
 *                                                                   *
 * This computer program is protected by copyright law and           *
 * international treaties. Unauthorized reproduction or distribution *
 * of this program, or any portion of it, may result in severe civil *
 * and criminal penalties, and will be prosecuted to the maximum     *
 * extent possible under the law.                                    *
 *                                                                   *
 *********************************************************************/
package com.nikondsl.spss.record;

import com.nikondsl.spss.ISPSSWriter;
import com.nikondsl.spss.IVariable;

import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.util.List;
import java.util.Map;

/**
 * <p>This class should be used to create a formatted data structure (in SPSS raw format).</p>
 * <p>It writes generated bytes to defined output SPSS stuctured data.</p>
 * First at all, this XPorter provides you two options to add data to create SPSS data file - automatic and manual.
 * Automatic method means that you have to define the exact value of cases, opposite to manual, which means
 * you can add as many SPSS cases as you want without knowing the right value of SPSS cases.
 * <p>
 * At first you should create an instance of working class named ISPSSWriter by calling appropriate
 * createWriter() method.
 * Due to SPSS raw data file format we have to create 3 different sections in file:
 * <ul><li>common definition (like file label and document description), <li>variable definitions, <li>cases definition</ul>
 * <p>It makes us to call several important methods.</p>
 * <p>For the short <b>AUTOMATIC mode</b> instance (see full example at {@link AutomaticModeDemo}):</p>
 * <pre>
 * ISPSSWriter writer=SPSSFacade.createWriter("UTF-8", " Demo", os);
 * List<IVariable> variables = defineVariables1();
 * writer.addVariables(variables);
 * writer.setLineByLineMode(true);
 * writer.setNumberOfCases(numberOfCases);
 * writer.generateDictionary(null);//Note: null means you can add SPSS cases several times by calling generate(List<SPSSCase> cases)
 * while(numberOfCases>0){
 * List<SPSSCase> cases=defineCases();
 * writer.generate(cases);
 * numberOfCases-=cases.size();
 * }
 * writer.generateFinishSection();
 * writer.close();
 * </pre>
 *  <p>The main advantage for automatic mode is that you can generate cases and generate file concurrency,
 *  unlike manual method, when you have to have all SPSS cases generated before writing to the data file.
 *  The main advantage of manual mode that it is the simpliest way to create SPSS data file.</p>
 * <p></p>
 *  <p>For the short <b>MANUAL mode</b> instance (see full example at {@link ManualModeDemo}):</p>
 * <pre>
 * ISPSSWriter writer=SPSSFacade.createWriter("UTF-8", " Demo", os);
 * List<IVariable> variables = defineVariables1();
 * writer.addVariables(variables);
 * List<SPSSCase> cases=defineCases();
 * writer.generate(cases);
 * writer.generateFinishSection();
 * writer.close();
 * </pre>
 *
 * <p>To define a variable you have to use correspondent createVariable() method.<p>
 * <p>To add defined variable you may use</p> {@link ISPSSWriter}.addVariables()
 * <p>Note:</p> you are supposed to call the close() method in order to get the generated file.
 */
public class SPSSFacade {

    /**
     * creates SPSSWriter exemplar with given {@link OutputStream} to write
     *
     * @param charset              type, may be "UTF-8", etc.
     * @param header
     * @param externalOutputStream
     * @return
     */
    public static ISPSSWriter createWriter(String charset, String header, OutputStream externalOutputStream) {
        return new SPSSWriter(charset, header, externalOutputStream);
    }

    /**
     * creates SPSSWriter exemplar with {@link ByteArrayOutputStream} by default as {@link OutputStream} to write to
     *
     * @param charset type, may be "UTF-8", etc.
     * @param header
     * @return
     */
    public static ISPSSWriter createWriter(String charset, String header) {
        return new SPSSWriter(charset, header);
    }

    /**
     * creates SPSSVariable with given {@link VariableType} type
     *
     * @param writer where variables should be defined
     * @param type   of variable {@link VariableType} for defining variable type
     * @param name   of variable
     * @param label  of variable
     * @param labels for values of this variable
     * @return
     * @throws UnsupportedEncodingException
     */
    public static IVariable createVariable(ISPSSWriter writer, VariableType type, String name, String label, Map<Double, String> labels) throws UnsupportedEncodingException {
        return getWriter(writer).createVariable(type, name, label, labels);
    }

    /**
     * creates String SPSSVariable with given name and label
     * It is common used as text variable with fixed length (by default 0)
     *
     * @param writer
     * @param name
     * @param label
     * @return
     * @throws UnsupportedEncodingException
     */
    public static IVariable createVariable(ISPSSWriter writer, String name, String label) throws UnsupportedEncodingException {
        return getWriter(writer).createVariable(name, label);
    }

    /**
     * creates String SPSSVariable with given name and label and length
     * It is common used as text variable with fixed length
     *
     * @param writer
     * @param name
     * @param label
     * @param width
     * @return
     * @throws UnsupportedEncodingException
     */
    public static IVariable createVariable(ISPSSWriter writer, String name, String label, int width) throws UnsupportedEncodingException {
        return getWriter(writer).createVariable(name, label, width);
    }

    private static SPSSWriter getWriter(ISPSSWriter writer) {
        if (writer == null)
            throw new IllegalStateException("Before creating a variable you should have a writer created. Call one of createWriter() methods first.");
        return ((SPSSWriter) writer);
    }

    /**
     * returnes SPSS variables. It is helper method. It is not neccessary for common use
     *
     * @param writer
     * @return
     */
    public static List<IVariable> getVariables(ISPSSWriter writer) {
        return getWriter(writer).getVariables();
    }

    /**
     * adds named sets of SPSS variables (see SPSS documentation for help)
     *
     * @param writer
     * @param map
     */
    public static void addVariablesSets(ISPSSWriter writer, Map<String, List<IVariable>> map) {
        writer.addVariablesSets(map);
    }

}
